name: CI for eProsima Integration Service Docs

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'

jobs:
  integration-service-docs_CI:
    runs-on: ubuntu-20.04
    container: ubuntu:focal

    steps:
      - uses: actions/checkout@v2
        with:
          path: .

      - name: Download required dependencies
        run: |
            apt update
            DEBIAN_FRONTEND=noninteractive apt install -y python3-pip python3-enchant git make doxygen
            pip3 install -I -r docs/requirements.txt

      - name: Build and test the documentation
        run: |
            READTHEDOCS=True IS_BRANCH=${{ github.head_ref }}  sphinx-build -b html -d build/doctrees docs build/html
            READTHEDOCS=True IS_BRANCH=${{ github.head_ref }}  doc8 --max-line-length 200 docs
            READTHEDOCS=True IS_BRANCH=${{ github.head_ref }}  sphinx-build -W --keep-going -b spelling -d build/doctrees docs build/spelling
