name: CI for eProsima Integration Service Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  integration-service-docs_CI:
    runs-on: ubuntu-20.04
    container: ubuntu:focal

    steps:
      - uses: actions/checkout@v2
        with:
          path: src/integration-service-docs

      - name: Download required dependencies
        run: |
            apt update
            DEBIAN_FRONTEND=noninteractive apt install -y python3-pip python3-enchant git make
            pip3 install -I -r src/integration-service-docs/docs/requirements.txt

      - name: Build and test the documentation
        run: |
            cd src/integration-service-docs/
            make test
