name: CI for eProsima Integration Service Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  integration-service-docs_CI:
    runs-on: ubuntu-20.04
    container: ubuntu:focal

    steps:
      - uses: actions/checkout@v2
        with:
          path: .

      - name: Download required dependencies
        run: |
            apt update
            DEBIAN_FRONTEND=noninteractive apt install -y python3-pip python3-enchant git make
            pip3 install -I -r docs/requirements.txt

      - name: Build and test the documentation
        run: |
            READTHEDOCS=True sphinx-build -b html -d build/doctrees docs build/html
            READTHEDOCS=True doc8 --max-line-length 200 docs
            READTHEDOCS=True sphinx-build -W --keep-going -b spelling -d build/doctrees docs build/spelling
